---

galaxy_info:
  author: IBM
  description: Role that adds system alerts snmp
  company: IBM

  license: Apache

  min_ansible_version: 2.9
  platforms:
    - name: GenericLinux
      versions:
        - any

  galaxy_tags:
  - isam
  - ibm
  - snmp

dependencies:
  - ibm.isam.common_handlers
