# Default variables for configuration of reverse proxy junctions
instances: []

# Configuration entry to control, if not listed junction servers should be deleted on the server
delete_junction_server: false
delete_junctions: false
force: false
