- name: Enable Management Authorization (Role Based Access)
  ibm.isam.isam:
    log: "{{ log_level | default('INFO') }}"
    force: "{{ force | default(False) }}"
    action: ibmsecurity.isam.base.management_authorization.config.set
    isamapi:
      enforcing: "{{ switch_auth_enable }}"
  notify: Commit Changes